spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_platform?createDatabaseIfNotExist=true
    username: root
    password: Yasith@1.

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true